apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: docker.io/learninglight/myapp:v1.1
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          value: "root"
        - name: MYSQL_ROOT_PASSWORD
          value: "passw0rd"
        - name: DB_HOST
          value: "10.109.210.249"
        - name: DB_PORT
          value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80          # External port for the LoadBalancer
    targetPort: 5000  # Port inside the container
